package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/lib/pq"
)

// CriarBancoCompleto cria todo o banco de dados com estrutura e dados das falhas EDP
func CriarBancoCompleto() error {
	// Configuração do PostgreSQL a partir de variáveis de ambiente
	host := os.Getenv("DB_HOST")
	if host == "" {
		host = "localhost"
	}
	port := os.Getenv("DB_PORT")
	if port == "" {
		port = "5432"
	}
	user := os.Getenv("DB_USER")
	if user == "" {
		user = "postgres"
	}
	password := os.Getenv("DB_PASSWORD")
	if password == "" {
		log.Fatal("❌ DB_PASSWORD não configurado no .env")
	}
	dbname := os.Getenv("DB_NAME")
	if dbname == "" {
		dbname = "falhas_edp"
	}

	fmt.Println("🚀 CRIANDO BANCO DE DADOS EDP - SISTEMA DE FALHAS")
	fmt.Println("================================================")

	// 1. Conectar ao postgres para criar o banco
	fmt.Println("🔌 Conectando ao PostgreSQL...")
	connStrPostgres := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=postgres sslmode=disable",
		host, port, user, password)

	db, err := sql.Open("postgres", connStrPostgres)
	if err != nil {
		return fmt.Errorf("erro ao conectar: %v", err)
	}
	defer db.Close()

	// 2. Criar banco se não existir
	var exists bool
	err = db.QueryRow("SELECT EXISTS(SELECT datname FROM pg_catalog.pg_database WHERE datname = $1)", dbname).Scan(&exists)
	if err != nil {
		return fmt.Errorf("erro ao verificar banco: %v", err)
	}

	if !exists {
		fmt.Printf("📦 Criando banco '%s'...\n", dbname)
		_, err = db.Exec(fmt.Sprintf("CREATE DATABASE %s OWNER %s", dbname, user))
		if err != nil {
			return fmt.Errorf("erro ao criar banco: %v", err)
		}
		fmt.Printf("✅ Banco '%s' criado!\n", dbname)
	} else {
		fmt.Printf("✅ Banco '%s' já existe\n", dbname)
	}

	db.Close()

	// 3. Conectar ao banco falhas_edp
	fmt.Println("🗄️ Conectando ao banco falhas_edp...")
	connStrDB := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	dbFalhas, err := sql.Open("postgres", connStrDB)
	if err != nil {
		return fmt.Errorf("erro ao conectar ao banco falhas_edp: %v", err)
	}
	defer dbFalhas.Close()

	// 4. Criar tabelas
	fmt.Println("📋 Criando estrutura das tabelas...")
	err = criarTabelas(dbFalhas)
	if err != nil {
		return err
	}

	// 5. Inserir dados iniciais
	fmt.Println("📊 Inserindo dados das eclusas...")
	err = inserirDadosIniciais(dbFalhas)
	if err != nil {
		return err
	}

	// 6. Inserir todas as falhas e eventos da Régua
	fmt.Println("⚙️ Inserindo falhas e eventos da Eclusa da Régua...")
	err = inserirFalhasEventosRegua(dbFalhas)
	if err != nil {
		return err
	}

	fmt.Println("\n✅ BANCO CRIADO COM SUCESSO!")
	fmt.Println("===========================")
	exibirEstatisticas(dbFalhas)

	return nil
}

// existeTabela verifica se uma tabela já existe no banco de dados
func existeTabela(db *sql.DB, nomeTabela string) bool {
	var existe bool
	query := `SELECT EXISTS (
		SELECT FROM information_schema.tables 
		WHERE table_schema = 'public' 
		AND table_name = $1
	)`
	err := db.QueryRow(query, nomeTabela).Scan(&existe)
	if err != nil {
		log.Printf("Erro ao verificar se tabela %s existe: %v", nomeTabela, err)
		return false
	}
	return existe
}

func criarTabelas(db *sql.DB) error {
	// Verificar e criar Tabela de Eclusas
	if existeTabela(db, "eclusas") {
		fmt.Println("  ✅ Tabela 'eclusas' já existe")
	} else {
		fmt.Println("  📋 Criando tabela 'eclusas'...")
		_, err := db.Exec(`
		CREATE TABLE eclusas (
			id SERIAL PRIMARY KEY,
			codigo VARCHAR(20) UNIQUE NOT NULL,
			nome VARCHAR(100) NOT NULL,
			localizacao VARCHAR(200),
			ativa BOOLEAN DEFAULT true,
			created_at TIMESTAMP DEFAULT NOW()
		)`)
		if err != nil {
			return fmt.Errorf("erro ao criar tabela eclusas: %v", err)
		}
		fmt.Println("  ✅ Tabela 'eclusas' criada com sucesso!")
	}

	// Verificar e criar Tabela de Setores
	if existeTabela(db, "setores") {
		fmt.Println("  ✅ Tabela 'setores' já existe")
	} else {
		fmt.Println("  📋 Criando tabela 'setores'...")
		_, err := db.Exec(`
		CREATE TABLE setores (
			id SERIAL PRIMARY KEY,
			codigo VARCHAR(50) UNIQUE NOT NULL,
			nome VARCHAR(100) NOT NULL,
			cor_tema VARCHAR(50),
			created_at TIMESTAMP DEFAULT NOW()
		)`)
		if err != nil {
			return fmt.Errorf("erro ao criar tabela setores: %v", err)
		}
		fmt.Println("  ✅ Tabela 'setores' criada com sucesso!")
	}

	// Verificar e criar Tabela de Definições de Falhas/Eventos
	if existeTabela(db, "definicoes_falhas") {
		fmt.Println("  ✅ Tabela 'definicoes_falhas' já existe")
	} else {
		fmt.Println("  📋 Criando tabela 'definicoes_falhas'...")
		_, err := db.Exec(`
		CREATE TABLE definicoes_falhas (
			id SERIAL PRIMARY KEY,
			eclusa_id INTEGER REFERENCES eclusas(id),
			setor_id INTEGER REFERENCES setores(id),
			codigo VARCHAR(50) NOT NULL,
			tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('FALHA', 'EVENTO')),
			descricao TEXT NOT NULL,
			prioridade VARCHAR(20) NOT NULL DEFAULT 'MEDIA' CHECK (prioridade IN ('ALTA', 'MEDIA', 'BAIXA')),
			point_index INTEGER NOT NULL,
			classe_mensagem VARCHAR(100),
			word_index INTEGER,
			bit_index INTEGER,
			ativa BOOLEAN DEFAULT true,
			created_at TIMESTAMP DEFAULT NOW(),
			UNIQUE(eclusa_id, point_index)
		)`)
		if err != nil {
			return fmt.Errorf("erro ao criar tabela definicoes_falhas: %v", err)
		}
		fmt.Println("  ✅ Tabela 'definicoes_falhas' criada com sucesso!")
	}

	// Verificar e criar Tabela de Ocorrências
	if existeTabela(db, "ocorrencias_falhas") {
		fmt.Println("  ✅ Tabela 'ocorrencias_falhas' já existe")
	} else {
		fmt.Println("  📋 Criando tabela 'ocorrencias_falhas'...")
		_, err := db.Exec(`
		CREATE TABLE ocorrencias_falhas (
			id BIGSERIAL PRIMARY KEY,
			definicao_id INTEGER REFERENCES definicoes_falhas(id),
			status VARCHAR(20) NOT NULL DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'RESOLVIDO', 'EM_ANALISE')),
			timestamp_inicio TIMESTAMP NOT NULL DEFAULT NOW(),
			timestamp_fim TIMESTAMP,
			dados_contexto JSONB,
			resolvido_por VARCHAR(100),
			observacoes TEXT,
			created_at TIMESTAMP DEFAULT NOW()
		)`)
		if err != nil {
			return fmt.Errorf("erro ao criar tabela ocorrencias_falhas: %v", err)
		}
		fmt.Println("  ✅ Tabela 'ocorrencias_falhas' criada com sucesso!")
	}

	// Índices
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_ocorrencias_timestamp ON ocorrencias_falhas(timestamp_inicio DESC)`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_ocorrencias_status ON ocorrencias_falhas(status)`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_definicoes_eclusa_setor ON definicoes_falhas(eclusa_id, setor_id)`)

	fmt.Println("✅ Tabelas criadas com sucesso!")
	return nil
}

func inserirDadosIniciais(db *sql.DB) error {
	// Verificar e inserir Eclusas
	var countEclusas int
	db.QueryRow("SELECT COUNT(*) FROM eclusas").Scan(&countEclusas)
	
	if countEclusas > 0 {
		fmt.Printf("  ✅ Eclusas já existem (%d registros)\n", countEclusas)
	} else {
		fmt.Println("  📋 Inserindo dados das eclusas...")
		eclusas := []struct {
			codigo, nome, localizacao string
		}{
			{"REGUA", "Eclusa da Régua", "Rio Douro - Peso da Régua"},
			{"POCINHO", "Eclusa do Pocinho", "Rio Douro - Pocinho"},
			{"VALEIRA", "Eclusa da Valeira", "Rio Douro - Valeira"},
			{"CARRAPATELO", "Eclusa de Carrapatelo", "Rio Douro - Carrapatelo"},
			{"CRESTUMA", "Eclusa de Crestuma", "Rio Douro - Crestuma"},
		}

		for _, eclusa := range eclusas {
			_, err := db.Exec(`
				INSERT INTO eclusas (codigo, nome, localizacao) VALUES ($1, $2, $3)`,
				eclusa.codigo, eclusa.nome, eclusa.localizacao)
			if err != nil {
				return fmt.Errorf("erro ao inserir eclusa %s: %v", eclusa.codigo, err)
			}
		}
		fmt.Println("  ✅ Eclusas inseridas com sucesso!")
	}

	// Verificar e inserir Setores
	var countSetores int
	db.QueryRow("SELECT COUNT(*) FROM setores").Scan(&countSetores)
	
	if countSetores > 0 {
		fmt.Printf("  ✅ Setores já existem (%d registros)\n", countSetores)
	} else {
		fmt.Println("  📋 Inserindo dados dos setores...")
		setores := []struct {
			codigo, nome, cor string
		}{
			{"ENCHIMENTO", "Enchimento", "edp-cobalt"},
			{"ESVAZIAMENTO", "Esvaziamento", "edp-violet"},
			{"PORTAJUSANTE", "Porta Jusante", "edp-marine"},
			{"PORTAMONTANTE", "Porta Montante", "edp-spruce"},
			{"COMANDO_ECLUSA", "Comando Eclusa", "edp-electric"},
			{"ESGOTO_DRENAGEM", "Esgoto Drenagem", "edp-seaweed"},
		}

		for _, setor := range setores {
			_, err := db.Exec(`
				INSERT INTO setores (codigo, nome, cor_tema) VALUES ($1, $2, $3)`,
				setor.codigo, setor.nome, setor.cor)
			if err != nil {
				return fmt.Errorf("erro ao inserir setor %s: %v", setor.codigo, err)
			}
		}
		fmt.Println("  ✅ Setores inseridos com sucesso!")
	}

	fmt.Println("✅ Dados iniciais verificados/inseridos!")
	return nil
}

func inserirFalhasEventosRegua(db *sql.DB) error {
	// Verificar se as definições já existem
	var countDefinicoes int
	db.QueryRow("SELECT COUNT(*) FROM definicoes_falhas WHERE eclusa_id = (SELECT id FROM eclusas WHERE codigo = 'REGUA')").Scan(&countDefinicoes)
	
	if countDefinicoes > 0 {
		fmt.Printf("  ✅ Falhas e eventos da Régua já existem (%d registros)\n", countDefinicoes)
		return nil
	}

	fmt.Println("  📋 Inserindo falhas e eventos da Régua...")
	
	// Buscar ID da eclusa Régua
	var eclusa_id int
	err := db.QueryRow("SELECT id FROM eclusas WHERE codigo = 'REGUA'").Scan(&eclusa_id)
	if err != nil {
		return fmt.Errorf("eclusa REGUA não encontrada: %v", err)
	}

	// DADOS COMPLETOS: 736 FALHAS E EVENTOS DA ECLUSA DA RÉGUA
	type RegistroFalhaEvento struct {
		ID             int
		Descricao      string
		Setor          string
		Tipo           string
		ClasseMensagem string
	}

	// TODOS OS 736 REGISTROS COMPLETOS (496 FALHAS + 240 EVENTOS)
	registros := []RegistroFalhaEvento{
		// ==================== FALHAS ENCHIMENTO (1-64) ====================
		{1, "DISPARO PROTEÇÃO 24VDC ENTRADAS ANALÓGICAS", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{2, "DISPARO PROTEÇÃO DESCARREGADAOR SOBRETENSÕES", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{3, "DEFEITO DESCARREGADOR SOBRETENSÕES", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{4, "DISPARO PROTEÇÃO ALIM. ANALISADOR ENERGIA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{5, "FALTA ALIMENTAÇÃO 220 VDC", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{6, "FALHA COMUNICAÇÃO COM SALA DE COMANDO", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{7, "BY-PASS CONDIÇÕES REMOTAS ABERTURA COMPORTAS ATIVADO!!!!!", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{8, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{9, "EMERGÊNCIA ATIVADA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{10, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 400VAC/24VDC", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{11, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 220VDC/24VDC", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{12, "DISPARO INTERRUPTOR GERAL ALIMENTAÇÃO 3X400VAC", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{13, "FALTA ALIMENTAÇÃO FORÇA MOTRIZ 3X400VAC", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{14, "DISPARO PROTEÇÃO 24VDC ENTRADAS DIGITAIS", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{15, "DISPARO PROTEÇÃO 24VDC SAIDAS DIGITAIS", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{16, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{17, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{18, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{19, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{20, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{21, "DEFEITO AUTOMATO ERRO DIAGNOSTICO", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{22, "DEFEITO AUTOMATO ERRO PROGRAMA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{23, "DEFEITO AUTOMATO ERRO MODULOS", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{24, "DEFEITO AUTOMATO ERRO BASTIDOR", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{25, "DEFEITO RESPOSTA DE MARCHA BOMBA A COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{26, "DEFEITO ARRANCADOR SUAVE BOMBA A COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{27, "DISPARO PROTEÇÃO BOMBA A COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{28, "DISPARO PROTEÇÃO VALVULA DISTRIBUIÇÃO COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{29, "DISPARO PROTEÇÃO VALVULA DESCIDA COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{30, "DEFEITO MEDIDA DE POSIÇÃO COMPORTA DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{31, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{32, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{33, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{34, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{35, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{36, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{37, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{38, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{39, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{40, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{41, "DEFEITO RESPOSTA DE MARCHA BOMBA B COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{42, "DEFEITO ARRANCADOR SUAVE BOMBA B COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{43, "DISPARO PROTEÇÃO BOMBA B COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{44, "DISPARO PROTEÇÃO VALVULA DISTRIBUIÇÃO COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{45, "DISPARO PROTEÇÃO VALVULA DESCIDA COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{46, "DEFEITO MEDIDA DE POSIÇÃO COMPORTA ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{47, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{48, "RESERVA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{49, "VELOCIDADE ALTA 2º PATAMAR ABERTURA RAPIDA COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{50, "VELOCIDADE BAIXA 2º PATAMAR ABERTURA RAPIDA COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{51, "VELOCIDADE ALTA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{52, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{53, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{54, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{55, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{56, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{57, "VELOCIDADE ALTA 1º PATAMAR ABERTURA LENTA COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{58, "VELOCIDADE BAIXA 1º PATAMAR ABERTURA LENTA COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{59, "VELOCIDADE ALTA 2º PATAMAR ABERTURA RAPIDA COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{60, "VELOCIDADE BAIXA 2º PATAMAR ABERTURA RAPIDA COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{61, "VELOCIDADE ALTA FECHO COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{62, "VELOCIDADE BAIXA FECHO COMPORTA A DIREITA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{63, "VELOCIDADE ALTA 1º PATAMAR ABERTURA LENTA COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},
		{64, "VELOCIDADE BAIXA 1º PATAMAR ABERTURA LENTA COMPORTA B_ESQUERDA", "ENCHIMENTO", "FALHA", "RG_ALARME_ENCHIMENTO"},

		// ==================== FALHAS ESVAZIAMENTO (65-128) ====================
		{65, "DISPARO PROTEÇÃO 24VDC ENTRADAS ANALÓGICAS", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{66, "DISPARO PROTEÇÃO DESCARREGADAOR SOBRETENSÕES", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{67, "DEFEITO DESCARREGADOR SOBRETENSÕES", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{68, "DISPARO PROTEÇÃO ALIM. ANALISADOR ENERGIA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{69, "FALTA ALIMENTAÇÃO 220 VDC", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{70, "FALHA COMUNICAÇÃO COM SALA DE COMANDO", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{71, "BY-PASS CONDIÇÕES REMOTAS ABERTURA COMPORTAS ATIVADO!!!!!", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{72, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{73, "EMERGÊNCIA ATIVADA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{74, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 400VAC/24VDC", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{75, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 220VDC/24VDC", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{76, "DISPARO INTERRUPTOR GERAL ALIMENTAÇÃO 3X400VAC", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{77, "FALTA ALIMENTAÇÃO FORÇA MOTRIZ 3X400VAC", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{78, "DISPARO PROTEÇÃO 24VDC ENTRADAS DIGITAIS", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{79, "DISPARO PROTEÇÃO 24VDC SAIDAS DIGITAIS", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{80, "DISPARO PROTEÇÃO 24VDC QUADRO FORÇA MOTRIZ", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{81, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{82, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{83, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{84, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{85, "DEFEITO AUTOMATO ERRO DIAGNOSTICO", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{86, "DEFEITO AUTOMATO ERRO PROGRAMA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{87, "DEFEITO AUTOMATO ERRO MODULOS", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{88, "DEFEITO AUTOMATO ERRO BASTIDOR", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{89, "DEFEITO RESPOSTA DE MARCHA BOMBA A COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{90, "DEFEITO ARRANCADOR SUAVE BOMBA A COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{91, "DISPARO PROTEÇÃO BOMBA A COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{92, "DISPARO PROTEÇÃO VALVULA DISTRIBUIÇÃO COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{93, "DISPARO PROTEÇÃO VALVULA DESCIDA COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{94, "DEFEITO MEDIDA DE POSIÇÃO COMPORTA DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{95, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{96, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{97, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{98, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{99, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{100, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{101, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{102, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{103, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{104, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{105, "DEFEITO RESPOSTA DE MARCHA BOMBA B COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{106, "DEFEITO ARRANCADOR SUAVE BOMBA B COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{107, "DISPARO PROTEÇÃO BOMBA A COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{108, "DISPARO PROTEÇÃO VALVULA DISTRIBUIÇÃO COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{109, "DISPARO PROTEÇÃO VALVULA DESCIDA COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{110, "DEFEITO MEDIDA DE POSIÇÃO COMPORTA ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{111, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{112, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{113, "VELOCIDADE ALTA 2º PATAMAR ABERTURA RAPIDA COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{114, "VELOCIDADE BAIXA 2º PATAMAR ABERTURA RAPIDA COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{115, "VELOCIDADE ALTA FECHO COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{116, "VELOCIDADE BAIXA FECHO COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{117, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{118, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{119, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{120, "RESERVA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{121, "VELOCIDADE ALTA 1º PATAMAR ABERTURA LENTA COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{122, "VELOCIDADE BAIXA 1º PATAMAR ABERTURA LENTA COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{123, "VELOCIDADE ALTA 2º PATAMAR ABERTURA RAPIDA COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{124, "VELOCIDADE BAIXA 2º PATAMAR ABERTURA RAPIDA COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{125, "VELOCIDADE ALTA FECHO COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{126, "VELOCIDADE BAIXA FECHO COMPORTA A DIREITA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{127, "VELOCIDADE ALTA 1º PATAMAR ABERTURA LENTA COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},
		{128, "VELOCIDADE BAIXA 1º PATAMAR ABERTURA LENTA COMPORTA B_ESQUERDA", "ESVAZIAMENTO", "FALHA", "RG_ALARME_ESVAZIAMENTO"},

		// ==================== FALHAS PORTA JUSANTE (129-208) ====================
		{129, "DISPARO PROTEÇÃO 24VDC QUADROS FORÇA MOTRIZ", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{130, "DEFEITO DESNIVELAMENTO PORTA - STOP", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{131, "ALARME DESNIVELAMENTO PORTA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{132, "PARAGEM MARGEM DIREITA ATIVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{133, "PARAGEM QUADRO ATIVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{134, "PARAGEM MARGEM ESQUERDA ATIVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{135, "FALHA COMUNICAÇÃO COM SALA DE COMANDO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{136, "DEFEITO PROTEÇÃO SOBRETENSÃO ALIMENTAÇÃO 3X400VAC", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{137, "EMERGÊNCIA ATIVADA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{138, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 400VAC/24VDC", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{139, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 220VDC/24VDC", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{140, "DISPARO INTERRUPTOR GERAL ALIMENTAÇÃO 3X400VAC", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{141, "FALTA ALIMENTAÇÃO FORÇA MOTRIZ 3X400VAC", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{142, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{143, "DISPARO PROTEÇÃO 24VDC ENTRADAS DIGITAIS", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{144, "DISPARO PROTEÇÃO 24VDC SAIDAS DIGITAIS", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{145, "DISPARO PROTEÇÃO MOTOR MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{146, "DISPARO PROTEÇÃO MOTOR MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{147, "DISPARO PROTEÇÃO FREIO MOTOR MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{148, "DISPARO PROTEÇÃO FREIO MOTOR MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{149, "DISPARO PROTEÇÃO FREIO HIDR. SEGURANÇA MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{150, "DISPARO PROTEÇÃO FREIO HIDR. SEGURANÇA MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{151, "FALTA IGULDADE DE NIVEIS- ORDEM RECUSADA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{152, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{153, "DETEÇÃO ESFORÇO SUBIDA MARGEM DIREITA MONTANTE_PORTA JUSANTE", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{154, "DETEÇÃO ESFORÇO SUBIDA MARGEM DIREITA JUSANTE-PORTA JUSANTE", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{155, "DETEÇÃO ESFORÇO DESCIDA MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{156, "DETEÇÃO ESFORÇO SUBIDA MARGEM ESQUERDA MONTANTE-PORTA JUSANTE", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{157, "DETEÇÃO ESFORÇO SUBIDA MARGEM ESQUERDA JUSANTE-PORTA JUSANTE", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{158, "DETEÇÃO ESFORÇO DESCIDA MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{159, "DEFEITO PROTEÇÃO CONTRA SOBRETENSÕES CIRCUITOS DE COMANDO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{160, "DISPARO PROTEÇÃO DESCARREGADOR SOBRETENSÃO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{161, "FREIOS DE SEGURANÇA ATIVADOS MANUALMENTE!!", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{162, "LASER PORTA JUSANTE OBSTRUÇÃO DETECTADA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{163, "LASER PORTA JUSANTE LIMPEZA NECESSÁRIA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{164, "LASER PORTA JUSANTE DESLIGADO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{165, "ALARME DIFERENÇA DE POSIÇÃO ENTRE CONTRA PESO DIREITO E POSIÇÃO GUINCHO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{166, "ALARME DIFERENÇA DE POSIÇÃO ENTRE CONTRA PESO ESQUERDO E POSIÇÃO GUINCHO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{167, "BY-PASS CONDIÇÕES REMOTAS (IGUALDADE NIVEIS) SUBIDA ABERTURA ATIVADO!!!!", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{168, "BY-PASS CONDIÇÕES REMOTAS DESCIDA FECHO ATIVADO!!!!", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{169, "VARIADOR VELOCIDADE MOTOR DIREITO EM DEFEITO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{170, "VARIADOR VELOCIDADE MOTOR ESQUERDO EM DEFEITO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{171, "DISPARO PROTEÇÃO VENTILADOR MOTOR DIREITO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{172, "DISPARO PROTEÇÃO VENTILADOR MOTOR ESQUERDO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{173, "DISPARO PROTEÇÃO RESISTÊNCIAS MOTOR DIREITO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{174, "DISPARO PROTEÇÃO RESISTÊNCIAS MOTOR ESQUERDO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{175, "VARIADOR MOTOR DIREITO NÃO PRONTO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{176, "VARIADOR MOTOR ESQUERDO NÃO PRONTO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{177, "FALHA COMUNICAÇÃO ENCODER MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{178, "FALHA COMUNICAÇÃO ENCODER MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{179, "MEDIDA FORA LIMITES ENCODER MARGEM DIREITA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{180, "MEDIDA FORA LIMITES ENCODER MARGEM ESQUERDA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{181, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{182, "DEFEITO PRISÃO PORTA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{183, "FALHA COMUNICAÇÃO VARIADOR MESTRE MOTOR DIREITO - FUNC. AUTOMATICO FORA DE SERVIÇO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{184, "FALHA COMUNICAÇÃO VARIADOR ESCRAVO MOTOR ESQUERDO - FUNC. AUTOMATICO FORA DE SERVIÇO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{185, "OBSTRUÇÃO DO LADO DIREITO NO FECHO DA PORTA!! ACIONAR LIMPEZA.", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{186, "OBSTRUÇÃO DO LADO ESQUERDO NO FECHO DA PORTA!! ACIONAR LIMPEZA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{187, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{188, "BY-PASS LAYSER PORTA JUSANTE ATIVADO !!!", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{189, "DEFEITO AUTOMATO ERRO DIAGNOSTICO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{190, "DEFEITO AUTOMATO ERRO PROGRAMA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{191, "DEFEITO AUTOMATO ERRO MODULOS", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{192, "DEFEITO AUTOMATO ERRO BASTIDOR", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{193, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{194, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{195, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{196, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{197, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{198, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{199, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{200, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{201, "PARAGEM SALA DE COMANDO ATIVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{202, "PARAGEM QUADRO ATIVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{203, "ALARME DIFERENÇA ENTRE IGUALDADE DE NIVEIS UMN E AUTÓMATO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{204, "IGUALDADE DE NIVEIS DO AUTÓMATO FORA DE SERVIÇO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{205, "IGUALDADE DE NIVEIS DA UMN FORA DE SERVIÇO", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{206, "NÍVEL MINIMO COTA NAVEGAVEL JUSANTE-PORTA JUSANTE", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{207, "DISPARO PROTEÇÃO ANALIZADOR", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},
		{208, "RESERVA", "PORTAJUSANTE", "FALHA", "RG_ALARME_PORTAJUSANTE"},

		// ==================== FALHAS PORTA MONTANTE (209-304) ====================
		{209, "DISPARO PROTEÇÃO 24VDC QUADRO FORÇA MOTRIZ-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{210, "DEFEITO DESNIVELAMENTO PORTA - STOP @1%d@  mm", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{211, "ALARME DESNIVELAMENTO PORTA @1%d@  mm", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{212, "PARAGEM MARGEM DIREITA ATIVA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{213, "PARAGEM QUADRO ATIVA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{214, "PARAGEM MARGEM ESQUERDA ATIVA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{215, "FALHA COMUNICAÇÃO COM SALA DE COMANDO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{216, "DEFEITO PROTEÇÃO SOBRETENSÃO ALIMENTAÇÃO 3X400VAC", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{217, "EMERGÊNCIA ATIVADA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{218, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 400VAC/24VDC-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{219, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 220VDC/24VDC-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{220, "DISPARO INTERRUPTOR GERAL ALIMENTAÇÃO 3X400VAC-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{221, "FALTA ALIMENTAÇÃO FORÇA MOTRIZ 3X400VAC-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{222, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{223, "DISPARO PROTEÇÃO 24VDC ENTRADAS DIGITAIS-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{224, "DISPARO PROTEÇÃO 24VDC SAIDAS DIGITAIS-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{225, "DISPARO PROTEÇÃO MOTOR MARGEM DIREITA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{226, "DISPARO PROTEÇÃO MOTOR MARGEM ESQUERDA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{227, "DISPARO PROTEÇÃO FREIO MOTOR MARGEM DIREITA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{228, "DISPARO PROTEÇÃO FREIO MOTOR MARGEM ESQUERDA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{229, "DISPARO PROTEÇÃO FREIO HIDR. SEGURANÇA MARGEM DIREITA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{230, "DISPARO PROTEÇÃO FREIO HIDR. SEGURANÇA MARGEM ESQUERDA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{231, "FALTA IGULDADE DE NIVEIS- ORDEM RECUSADA-PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{232, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{233, "LASER PORTA MONTANTE OBSTRUÇÃO DETECTADA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{234, "LASER PORTA MONTANTE LIMPEZA NECESSÁRIA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{235, "LASER PORTA MONTANTE DESLIGADO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{236, "BY-PASS LAYSER PORTA MONTANTE ATIVADO !!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{237, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{238, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{239, "DEFEITO PROTEÇÃO CONTRA SOBRETENSÕES CIRCUITOS DE COMANDO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{240, "DISPARO PROTEÇÃO DESCARREGADOR SOBRETENSÃO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{241, "ENCARQUILHAMENTO CORRENTE GUINCHO MARGEM DIREITA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{242, "ENCARQUILHAMENTO CORRENTE GUINCHO MARGEM ESQUERDA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{243, "FREIOS DE SEGURANÇA ATIVADOS MANUALMENTE!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{244, "SEGURANÇA DETEÇÃO ENCARQUILHAMENTO DESATIVADA!!!!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{245, "ATENÇÃO!! PORTA DE MONTANTE FORA DE POSIÇÃO!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{246, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{247, "BY-PASS CONDIÇÕES REMOTAS SUBIDA - FECHO - ATIVADO!!!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{248, "BY-PASS CONDIÇÕES REMOTAS (IGUALD. NIVEIS) DESCIDA - ABERTURA - ATIVADO!!!!", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{249, "VARIADOR VELOCIDADE MOTOR DIREITO EM DEFEITO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{250, "VARIADOR VELOCIDADE MOTOR ESQUERDO EM DEFEITO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{251, "DISPARO PROTEÇÃO VENTILADOR MOTOR DIREITO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{252, "DISPARO PROTEÇÃO VENTILADOR MOTOR ESQUERDO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{253, "DISPARO PROTEÇÃO RESISTÊNCIAS MOTOR DIREITO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{254, "DISPARO PROTEÇÃO RESISTÊNCIAS MOTOR ESQUERDO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{255, "VARIADOR MOTOR DIREITO NÃO PRONTO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{256, "VARIADOR MOTOR ESQUERDO NÃO PRONTO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{257, "FALHA COMUNICAÇÃO ENCODER MARGEM DIREITA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{258, "FALHA COMUNICAÇÃO ENCODER MARGEM ESQUERDA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{259, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{260, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{261, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{262, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{263, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{264, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{265, "DEFEITO POSIÇÃO GUINCHO DIREITO EM RELAÇÃO À PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{266, "DEFEITO POSIÇÃO GUINCHO ESQUERDO EM RELAÇÃO À PORTA MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{267, "BY-PASS SEGURANÇA POSIÇÃO GUINCHO DIREITO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{268, "BY-PASS SEGURANÇA POSIÇÃO GUINCHO ESQUERDO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{269, "DEFEITO AUTOMATO ERRO DIAGNOSTICO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{270, "DEFEITO AUTOMATO ERRO PROGRAMA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{271, "DEFEITO AUTOMATO ERRO MODULOS", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{272, "DEFEITO AUTOMATO ERRO BASTIDOR", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{273, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{274, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{275, "MEDIDA FORA LIMITES ENCODER MARGEM DIREITA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{276, "MEDIDA FORA LIMITES ENCODER MARGEM ESQUERDA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{277, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{278, "DEFEITO PRISÃO PORTA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{279, "FALHA COMUNICAÇÃO VARIADOR ESCRAVO MOTOR DIREITO - FUNC. AUTOMATICO FORA DE SERVIÇO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{280, "FALHA COMUNICAÇÃO VARIADOR MESTRE MOTOR ESQUERDO - FUNC. AUTOMATICO FORA DE SERVIÇO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{281, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{282, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{283, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{284, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{285, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{286, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{287, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{288, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{289, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{290, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{291, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{292, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{293, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{294, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{295, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{296, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{297, "PARAGEM SALA DE COMANDO ATIVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{298, "PARAGEM QUADRO ATIVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{299, "IGUALDADE DE NIVEIS DO AUTÓMATO FORA DE SERVIÇO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{300, "IGUALDADE DE NIVEIS DA UMN FORA DE SERVIÇO", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{301, "NÍVEL MINIMO COTA NAVEGAVEL JUSANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{302, "NIVEL MINIMO COTA NAVEGAVEL A MONTANTE", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{303, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},
		{304, "RESERVA", "PORTAMONTANTE", "FALHA", "RG_ALARME_PORTAMONTANTE"},

		// ==================== FALHAS SALA DE COMANDO (305-400) ====================
		{305, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{306, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{307, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{308, "DEFEITO AUTOMATO ERRO DIAGNOSTICO - SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{309, "DEFEITO AUTOMATO ERRO ACESSO I/O", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{310, "DEFEITO AUTOMATO ERRO PROGRAMA - SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{311, "DEFEITO AUTOMATO ERRO MODULOS - SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{312, "DEFEITO AUTOMATO ERRO BASTIDOR - SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{313, "EMERGÊNCIA ATIVADA QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{314, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 220VDC/24VDC - QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{315, "DEFEITO/ALARME FONTE ALIMENTAÇÃO 400VAC/24VDC - QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{316, "DISPARO PROTEÇÃO 24VDC ENTRADAS DIGITAIS PLC QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{317, "DISPARO PROTEÇÃO 24VDC SAIDAS DIGITAIS PLC QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{318, "DISPARO PROTEÇÃO 24VDC ENTRADAS ANALOGICAS PLC QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{319, "DISPARO PROTEÇÃO 24VDC UNIDADE MEDIDA DE NÍVEL - QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{320, "FALTA ALIMENTAÇÃO 230VAC SEMAFOROS - QUADRO SALA DE COMANDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{321, "MN-SC- DEFEITO RELE IGUALDADE DE NÍVEIS JUSANTE - RELE FORÇADO!!!", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{322, "MN-SC- BY-PASS IGUALDADE DE NÍVEIS MONTANTE ATIVADO!!!", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{323, "MN-SC- DEFEITO RELE IGUALDADE DE NÍVEIS MONTANTE - RELE FORÇADO!!!", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{324, "MN-SC- DEFEITO RESPOSTA RELE IGUALDADE DE NÍVEIS JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{325, "MN-SC- DEFEITO RESPOSTA RELE IGUALDADE DE NÍVEIS MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{326, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{327, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{328, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{329, "MN-SC- DEFEITO SONDA MEDIDA DE NÍVELL JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{330, "MN-SC- DEFEITO SONDA MEDIDA DE NÍVEL CALDEIRA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{331, "MN-SC- DEFEITO SONDA MEDIDA DE NÍVEL MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{332, "MN-SC- COTA MAXIMA DE NAVEGAÇÃO A JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{333, "MN-SC- COTA MINIMA DE NAVEGAÇÃO A JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{334, "MN-SC- COTA MAXIMA DE NAVEGAÇÃO A MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{335, "MN-SC- COTA MINIMA DE NAVEGAÇÃO A MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{336, "MN-SC- BY-PASS IGUALDADE DE NÍVEIS JUSANTE ATIVADO!!!", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{337, "INUNDAÇÃO POÇO DOS CONTRAPESOS PORTA DE MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{338, "INUNDAÇÃO POÇO DOS CONTRAPESOS PORTA DE JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{339, "FALTA ALIMENTAÇÃO QUADRO CONTROLO INUNDAÇÃO CONTRAPESOS", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{340, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{341, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{342, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{343, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{344, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{345, "QUADRO SALA DE COMANDO - FALHA DE COMUNICAÇÃO COM QUADRO CIRCUITO ENCHIMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{346, "QUADRO SALA DE COMANDO - FALHA DE COMUNICAÇÃO COM QUADRO CIRCUITO ESVAZIAMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{347, "QUADRO SALA DE COMANDO - FALHA DE COMUNICAÇÃO COM QUADRO PORTA DE JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{348, "QUADRO SALA DE COMANDO - FALHA DE COMUNICAÇÃO COM QUADRO PORTA DE MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{349, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{350, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{351, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{352, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{353, "RADAR JUSANTE EM ERRO/FALHA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{354, "FALHA COMUNICAÇÃO COM RADAR JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{355, "RADAR CALDEIRA DIREITO EM ERRO/FALHA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{356, "FALHA COMUNICAÇÃO COM RADAR CALDEIRA DIREITO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{357, "RADAR CALDEIRA ESQUERDO EM ERRO/FALHA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{358, "FALHA COMUNICAÇÃO COM RADAR CALDEIRA ESQUERDO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{359, "RADAR MONTANTE EM ERRO/FALHA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{360, "FALHA COMUNICAÇÃO COM RADAR MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{361, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{362, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL CALDEIRA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{363, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{364, "FALHA COMUNICAÇÃO ENTRE PLC SALA COMANDO E GATEWAY PAINEIS", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{365, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{366, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{367, "FALHA COMUNICAÇÃO ENTRE PLC COMANDO E PLC CONTROLO LASER PORTA MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{368, "FALHA COMUNICAÇÃO ENTRE PLC COMANDO E PLC CONTROLO LASER PORTA JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{369, "ECLUSAGEM AUTOMÁTICA SUBIDA ABORTADA - FALHA RESPOSTA MARCHA ABERTURA ENCHIMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{370, "ECLUSAGEM AUTOMÁTICA SUBIDA ABORTADA - FALHA RESPOSTA MARCHA ABERTURA PORTA MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{371, "ECLUSAGEM AUTOMÁTICA SUBIDA ABORTADA - FALHA RESPOSTA MARCHA FECHO ENCHIMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{372, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - TEMPO MÁXIMO OPERAÇÃO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{373, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{374, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{375, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{376, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{377, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{378, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL CALDEIRA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{379, "FALHA COMUNICAÇÃO ENTRE GATEWAY E PAINEL MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{380, "FALHA COMUNICAÇÃO ENTRE PLC SALA COMANDO E GATEWAY PAINEIS", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{381, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{382, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{383, "FALHA COMUNICAÇÃO ENTRE PLC COMANDO E PLC CONTROLO LASER PORTA MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{384, "FALHA COMUNICAÇÃO ENTRE PLC COMANDO E PLC CONTROLO LASER PORTA JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{385, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALHA RESPOSTA MARCHA ABERTURA ESVAZIAMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{386, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALHA RESPOSTA MARCHA ABERTURA PORTA JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{387, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALHA RESPOSTA MARCHA FECHO ESVAZIAMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{388, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - TEMPO MÁXIMO OPERAÇÃO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{389, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{390, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{391, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{392, "RESERVA", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{393, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - DETEÇÃO CAMARAS MIC", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{394, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - DETEÇÃO FOTOCELULAS", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{395, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - DETEÇÃO LASER MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{396, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALTA CONDIÇÕES PRELIMINARES FECHO PORTA MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{397, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALTA CONDIÇÕES PRELIMINARES ABERTURA ESVAZIAMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{398, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALTA CONDIÇÕES PRELIMINARES ABERTURA PORTA JUSANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{399, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALTA CONDIÇÕES PRELIMINARES FECHO ESVAZIAMENTO", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},
		{400, "ECLUSAGEM AUTOMÁTICA DESCIDA ABORTADA - FALHA RESPOSTA MARCHA FECHO PORTA MONTANTE", "COMANDO_ECLUSA", "FALHA", "RG_ALARME_COMANDO_ECLUSA"},

		// ==================== FALHAS ESGOTO E DRENAGEM (401-496) ====================
		{401, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{402, "DISPARO DISJUNTOR QDI PROTEÇÃO 24 VDC ENTRADAS DIGITAIS PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{403, "DISPARO DISJUNTOR QAI PROTEÇÃO 24 VDC ENTRADAS ANALÓGICAS PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{404, "DISPARO DISJUNTOR QDO PROTEÇÃO 24 VDC SAÍDAS DIGITAIS PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{405, "DISPARO DISJUNTOR QCPUR PROTEÇÃO 24 VDC PLC RECURSO", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{406, "DEFEITO CONVERSOR TENSÃO PS1 230VAC/24VDC", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{407, "DEFEITO CONVERSOR TENSÃO PS2 220VDC/24VDC", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{408, "ARRANQUES FREQUENTES BOMBAS", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{409, "EMERGÊNCIA ACTIVADA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{410, "FALTA ALIMENTAÇÃO 3X400VAC QUADRO QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{411, "FALTA ALIMENTAÇÃO 3X400VAC QUADRO QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{412, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{413, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{414, "INTERRUPTOR Q0 CORTE GERAL QEBED1 DESLIGADO (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{415, "INTERRUPTOR Q0 CORTE GERAL QEBED2 DESLIGADO (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{416, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{417, "NÍVEL DO POÇO ALTO !!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{418, "NÍVEL DO POÇO MUITO ALTO !!!!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{419, "NÍVEL INUNDAÇÃO DO POÇO ATINGIDO !!!!!!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{420, "NÍVEL DO POÇO MUITO BAIXO !!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{421, "BOIA - NÍVEL DO POÇO INUNDAÇÃO !!! (ATIVADO POR BOIA)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{422, "SISTEMA EM MANUAL Á MAIS DE 15MN", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{423, "SISTEMA DESLIGADO !!!!!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{424, "FUNCIONAMENTO PROLONGADO BOMBAS", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{425, "DEFEITO I/O PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{426, "DEFEITO PROGRAMA PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{427, "DEFEITO MODULOS PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{428, "DEFEITO BASTIDOR PLC PRINCIPAL", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{429, "ALARME DIFERENÇA ENTRE MEDIDAS DE NÍVEL (SONDA DE SERVIÇO E SONDA DE RECURSO)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{430, "SEM MEDIDA DE NÍVEL!!!! AVARIA DAS DUAS SONDAS!!! FUNCIONAMENTO POR BOIAS!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{431, "DEFEITO/AVARIA SONDA MEDIDA DE NÍVEL DE SERVIÇO", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{432, "DEFEITO/AVARIA SONDA MEDIDA DE NÍVEL DE RECURSO", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{433, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{434, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{435, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{436, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{437, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{438, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{439, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{440, "NÍVEL BAIXO POR BOIA!!", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{441, "DEFEITO AUTÓMATO DE RECURSO S7-1200", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{442, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{443, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{444, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{445, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{446, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{447, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{448, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{449, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{450, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{451, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{452, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{453, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{454, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{455, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{456, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{457, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{458, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{459, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{460, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{461, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{462, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{463, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{464, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{465, "DEFEITO ARRANCADOR SUAVE ARC1 QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{466, "DEFEITO ARRANQUE PROLONGADO BOMBA 1 QEBED1", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{467, "ALARME INTENSIDADE ALTA BOMBA ESGOTO 1 QEBED1", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{468, "DISPARO POR INTENSIDADE ALTA BOMBA ESGOTO 1 QEBED1", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{469, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{470, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{471, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{472, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{473, "FALTA TENSÃO COMANDO 230VAC QEBED1 K1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{474, "DISPARO DISJUNTOR Q1 PROTEÇÃO POTÊNCIA ARRANCADOR QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{475, "DISPARO DISJUNTOR Q10 PROTEÇÃO COMANDO 230VAC ARRANCADOR QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{476, "DISPARO DISJUNTOR Q9 PROTEÇÃO SISTEMA DETEÇÃO CORRENTE RESIDUAL QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{477, "DISPARO POR DETEÇÃO CORRENTE RESIDUAL QEBED1 RC1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{478, "DEFEITO RESPOSTA DE MARCHA CONTATOR DE LINHA KM1 QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{479, "BOMBA 1 EM COMANDO DIRETO QEBED1", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{480, "DEFEITO RESPOSTA DE MARCHA ARRANCADOR SUAVE ARC1 QEBED1 (BOMBA 1)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{481, "DEFEITO ARRANCADOR SUAVE ARC2 QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{482, "DEFEITO ARRANQUE PROLONGADO BOMBA 2 QEBED2", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{483, "ALARME INTENSIDADE ALTA BOMBA 2 QEBED2", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{484, "DISPARO POR INTENSIDADE ALTA BOMBA 2 QEBED2", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{485, "BOMBA 2 EM COMANDO POR BOIAS", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{486, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{487, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{488, "RESERVA", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{489, "FALTA TENSÃO COMANDO 230VAC QEBED2 K1 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{490, "DISPARO DISJUNTOR Q1 PROTEÇÃO POTÊNCIA ARRANCADOR QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{491, "DISPARO DISJUNTOR Q10 PROTEÇÃO COMANDO 230VAC ARRANCADOR QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{492, "DISPARO DISJUNTOR Q9 PROTEÇÃO SISTEMA DETEÇÃO CORRENTE RESIDUAL QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{493, "DISPARO POR DETEÇÃO CORRENTE RESIDUAL QEBED2 RC2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{494, "DEFEITO RESPOSTA DE MARCHA CONTATOR DE LINHA KM1 QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{495, "BOMBA 2 EM COMANDO DIRETO QEBED2", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},
		{496, "DEFEITO RESPOSTA DE MARCHA ARRANCADOR SUAVE ARC1 QEBED2 (BOMBA 2)", "ESGOTO_DRENAGEM", "FALHA", "RG_ALARME_ESGOTO_DRENAGEM"},

		// ==================== EVENTOS ENCHIMENTO (497-544) ====================
		{497, "ORDEM LOCAL FECHO COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{498, "ORDEM LOCAL PARAGEM COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{499, "CONDIÇÃO PORTA JUSANTE FECHADA PRESENTE", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{500, "CONDIÇÃO CIRCUITO ESVAZIAMENTO FECHADO PRESENTE", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{501, "COMPORTA A DIREITA ABERTA    TEMPO ABERT.", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{502, "COMPORTA A DIREITA NA POSIÇÃO DE ESTABILIZAÇÃO  TEMPO ABERT.", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{503, "COMPORTA A DIREITA FECHADA   TEMPO FECHO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{504, "COMPORTA B ESQUERDA ABERTA    TEMPO ABERT.", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{505, "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{506, "SISTEMA EM MANUAL", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{507, "SISTEMA EM AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{508, "SISTEMA DESLIGADO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{509, "ORDEM REMOTA ABERTURA COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{510, "ORDEM REMOTA FECHO COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{511, "ORDEM REMOTA DE PARAGEM COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{512, "ORDEM LOCAL ABERTURA COMPORTAS", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{513, "COMPORTA A DIREITA SELECIONADA REMOTO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{514, "COMPORTA B ESQUERDA SELECIONADA REMOTO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{515, "COMPORTA A DIREITA A ABRIR - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{516, "COMPORTA B ESQUERDA A ABRIR - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{517, "COMPORTA A DIREITA A ABRIR SUBIDA RAPIDA - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{518, "COMPORTA B ESQUERDA A ABRIR SUBIDA RAPIDA - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{519, "COMPORTA A DIREITA A FECHAR - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{520, "COMPORTA B ESQUERDA A FECHAR - AUTOMATICO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{521, "COMPORTA B ESQUERDA NA POSIÇÃO DE ESTABILIZAÇÃO  TEMPO ABERT.", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{522, "COMPORTA B ESQUERDA FECHADA   TEMPO FECHO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{523, "BOMBA OLEO COMPORTA A DIREITA LIGADA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{524, "BOMBA OLEO COMPORTA B ESQUERDA LIGADA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{525, "COMPORTA A DIREITA A FECHAR", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{526, "COMPORTA B ESQUERDA A FECHAR", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{527, "COMPORTA A DIREITA SELECIONADA LOCAL", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{528, "COMPORTA B ESQUERDA SELECIONADA LOCAL", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{529, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{530, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{531, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{532, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{533, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{534, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{535, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{536, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{537, "COMPORTAS EM PROGRAMA DE LIMPEZA PORTA JUSANTE", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{538, "COMPORTA A DIREITA FORA DE SERVIÇO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{539, "COMPORTA B ESQUERDA FORA DE SERVIÇO", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{540, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{541, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{542, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{543, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},
		{544, "RESERVA", "ENCHIMENTO", "EVENTO", "RG_EVENTO_ENCHIMENTO"},

		// ==================== EVENTOS ESVAZIAMENTO (545-592) ====================
		{545, "ORDEM LOCAL FECHO COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{546, "ORDEM LOCAL PARAGEM COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{547, "CONDIÇÃO PORTA MONTANTE FECHADA PRESENTE", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{548, "CONDIÇÃO CIRCUITO ENCHIMENTO FECHADO PRESENTE", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{549, "COMPORTA A DIREITA ABERTA    TEMPO ABERT. @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{550, "COMPORTA A DIREITA NA POSIÇÃO DE ESTABILIZAÇÃO  TEMPO ABERT. @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{551, "COMPORTA A DIREITA FECHADA   TEMPO FECHO @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{552, "COMPORTA B ESQUERDA ABERTA    TEMPO ABERT. @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{553, "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{554, "SISTEMA EM MANUAL", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{555, "SISTEMA EM AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{556, "SISTEMA DESLIGADO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{557, "ORDEM REMOTA ABERTURA COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{558, "ORDEM REMOTA FECHO COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{559, "ORDEM REMOTA DE PARAGEM COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{560, "ORDEM LOCAL ABERTURA COMPORTAS", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{561, "COMPORTA A DIREITA SELECIONADA REMOTO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{562, "COMPORTA B ESQUERDA SELECIONADA REMOTO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{563, "COMPORTA A DIREITA A ABRIR - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{564, "COMPORTA B ESQUERDA A ABRIR - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{565, "COMPORTA A DIREITA A ABRIR SUBIDA RAPIDA - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{566, "COMPORTA B ESQUERDA A ABRIR SUBIDA RAPIDA - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{567, "COMPORTA A DIREITA A FECHAR - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{568, "COMPORTA B ESQUERDA A FECHAR - AUTOMATICO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{569, "COMPORTA B ESQUERDA NA POSIÇÃO DE ESTABILIZAÇÃO  TEMPO ABERT. @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{570, "COMPORTA B ESQUERDA FECHADA   TEMPO FECHO  @1%d@  seg", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{571, "BOMBA OLEO COMPORTA A DIREITA LIGADA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{572, "BOMBA OLEO COMPORTA B ESQUERDA LIGADA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{573, "COMPORTA A DIREITA A FECHAR", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{574, "COMPORTA B ESQUERDA A FECHAR", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{575, "COMPORTA A DIREITA SELECIONADA LOCAL", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{576, "COMPORTA B ESQUERDA SELECIONADA LOCAL", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{577, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{578, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{579, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{580, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{581, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{582, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{583, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{584, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{585, "COMPORTAS EM PROGRAMA DE LIMPEZA PORTA JUSANTE", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{586, "COMPORTA A DIREITA FORA DE SERVIÇO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{587, "COMPORTA B ESQUERDA FORA DE SERVIÇO", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{588, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{589, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{590, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{591, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},
		{592, "RESERVA", "ESVAZIAMENTO", "EVENTO", "RG_EVENTO_ESVAZIAMENTO"},

		// ==================== EVENTOS PORTA JUSANTE (593-624) ====================
		{593, "ORDEM DE PARAGEM BOTONEIRA QUADRO DE COMANDO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{594, "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM ESQUERDA", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{595, "PORTA ABERTA (SUBIDA) - FIM DE CURSO. POS.DIR", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{596, "PORTA ABERTA (SUBIDA) - POSIÇÃO.   POS.DIR", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{597, "PORTA FECHADA (DESCIDA) - FIM DE CURSO  POS.DIR", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{598, "PORTA FECHADA (DESCIDA) - POSIÇÃO.  POS.DIR", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{599, "ORDEM DE PARAGEM  DA PORTA - SALA DE COMANDO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{600, "ORDEM DE ABERTURA (SUBIDA) DA PORTA - SALA DE COMANDO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{601, "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{602, "SISTEMA EM MANUAL", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{603, "SISTEMA EM AUTOMATICO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{604, "SISTEMA DESLIGADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{605, "ORDEM DE ABERTURA (SUBIDA) DA PORTA POR BOTONEIRA LOCAL", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{606, "ORDEM DE FECHO (DESCIDA) DA PORTA  POR BOTONEIRA LOCAL", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{607, "PRESENÇA DE BOTONEIRA DE COMANDO LOCAL", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{608, "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM DIREITA", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{609, "NIVELAMENTO DA PORTA ATIVADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{610, "FREIO DE SEGURANÇA DIREITO FORÇADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{611, "FREIO DO MOTOR DIREITO FORÇADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{612, "FREIO DE SEGURANÇA ESQUERDO FORÇADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{613, "FREIO DO MOTOR ESQUERDO FORÇADO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{614, "RESERVA", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{615, "RESERVA", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{616, "RESERVA", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{617, "ORDEM DE FECHO (DESCIDA) DA PORTA  - SALA DE COMANDO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{618, "CONDIÇÕES REMOTAS DE ABERTURA PRESENTES (IGUALDADE DE NIVEIS)", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{619, "PORTA A ABRIR (A SUBIR)", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{620, "PORTA A FECHAR (A DESCER)", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{621, "PORTA A ABRIR (A SUBIR) EM AUTOMATICO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{622, "PORTA A FECHAR (A DESCER) EM AUTOMATICO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{623, "ORDEM DE ABERTURA (SUBIDA) DA PORTA POR BOTONEIRA DO QUADRO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},
		{624, "ORDEM DE FECHO (DESCIDA) DA PORTA  POR BOTONEIRA DO QUADRO", "PORTAJUSANTE", "EVENTO", "RG_EVENTO_PORTAJUSANTE"},

		// ==================== EVENTOS PORTA MONTANTE (625-656) ====================
		{625, "ORDEM DE PARAGEM BOTONEIRA QUADRO DE COMANDO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{626, "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM ESQUERDA", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{627, "PORTA FECHADA (SUBIDA) - FIM DE CURSO   POS.DIR - <field ref=\"0\" />mm   POS.ESQ - .<field ref=\"1\" />mm", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{628, "PORTA FECHADA (SUBIDA) - POSIÇÃO    POS.DIR - <field ref=\"0\" />mm   POS.ESQ - .<field ref=\"1\" />mm", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{629, "PORTA ABERTA (DESCIDA) - FIM DE CURSO   POS.DIR - <field ref=\"0\" />mm   POS.ESQ - .<field ref=\"1\" />mm", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{630, "PORTA ABERTA (DESCIDA) - POSIÇÃO   POS.DIR - <field ref=\"0\" />mm   POS.ESQ - .<field ref=\"1\" />mm", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{631, "ORDEM DE PARAGEM  DA PORTA - SALA DE COMANDO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{632, "ORDEM DE FECHO (SUBIDA) DA PORTA - SALA DE COMANDO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{633, "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{634, "SISTEMA EM MANUAL", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{635, "SISTEMA EM AUTOMATICO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{636, "SISTEMA DESLIGADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{637, "ORDEM DE FECHO (SUBIDA) DA PORTA POR BOTONEIRA LOCAL", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{638, "ORDEM DE ABERTURA (DESCIDA) DA PORTA  POR BOTONEIRA LOCAL", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{639, "PRESENÇA DE BOTONEIRA DE COMANDO LOCAL", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{640, "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM DIREITA", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{641, "NIVELAMENTO DA PORTA ATIVADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{642, "FREIO DE SEGURANÇA DIREITO FORÇADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{643, "FREIO DO MOTOR DIREITO FORÇADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{644, "FREIO DE SEGURANÇA ESQUERDO FORÇADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{645, "FREIO DO MOTOR ESQUERDO FORÇADO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{646, "RESERVA", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{647, "RESERVA", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{648, "RESERVA", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{649, "ORDEM DE ABERTURA (DESCIDA) DA PORTA  - SALA DE COMANDO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{650, "CONDIÇÕES REMOTAS DE ABERTURA PRESENTES (IGUALDADE DE NIVEIS)", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{651, "PORTA A FECHAR (A SUBIR)", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{652, "PORTA A ABRIR (A DESCER)", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{653, "PORTA A FECHAR (A SUBIR) EM AUTOMATICO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{654, "PORTA A ABRIR (A DESCER) EM AUTOMATICO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{655, "ORDEM DE FECHO (SUBIDA) DA PORTA POR BOTONEIRA DO QUADRO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},
		{656, "ORDEM DE ABERTURA (DESCIDA) DA PORTA  POR BOTONEIRA DO QUADRO", "PORTAMONTANTE", "EVENTO", "RG_EVENTO_PORTAMONTANTE"},

		// ==================== EVENTOS SALA DE COMANDO (657-704) ====================
		{657, "SAÍDA ECLUSA PARA MONTANTE AUTORIZADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{658, "ENTRADA ECLUSA POR MONTANTE INTERDITA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{659, "ENTRADA ECLUSA POR MONTANTE AUTORIZADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{660, "ENTRADA ECLUSA POR MONTANTE EM PREPARAÇÃO", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{661, "SAÍDA ECLUSA PARA JUSANTE INTERDITA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{662, "SAÍDA ECLUSA PARA JUSANTE AUTORIZADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{663, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{664, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{665, "IGUALDADE DE NIVEIS UMN A MONTANTE PRESENTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{666, "IGUALDADE DE NIVEIS UMN A JUSANTE PRESENTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{667, "IGUALDADE DE NIVEIS SALA DE COMANDO A MONTANTE PRESENTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{668, "IGUALDADE DE NIVEIS SALA DE COMANDO A JUSANTE PRESENTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{669, "ENTRADA ECLUSA POR JUSANTE INTERDITA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{670, "ENTRADA ECLUSA POR JUSANTE AUTORIZADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{671, "ENTRADA ECLUSA POR JUSANTE EM PREPARAÇÃO", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{672, "SAÍDA ECLUSA PARA MONTANTE INTERDITA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{673, "ECLUSAGEM AUTOMÁTICA DE SUBIDA PREPARADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{674, "ECLUSAGEM AUTOMÁTICA DE SUBIDA ATIVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{675, "ECLUSAGEM AUTOMÁTICA DE SUBIDA CONCLUIDA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{676, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{677, "ECLUSAGEM AUTOMÁTICA DE DESCIDA PREPARADA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{678, "ECLUSAGEM AUTOMÁTICA DE DESCIDA ATIVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{679, "ECLUSAGEM AUTOMÁTICA DE DESCIDA CONCLUIDA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{680, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{681, "CAMARAS - DETEÇÃO BARCO GRANDE A JUSANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{682, "CAMARAS - DETEÇÃO BARCO PEQUENO A JUSANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{683, "CAMARAS - DETEÇÃO BARCO PEQUENO A MONTANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{684, "CAMARAS - DETEÇÃO BARCO GRANDE A MONTANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{685, "CAMARAS - DETEÇÃO BARCO NA CALDEIRA FORA DOS LIMITES A MONTANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{686, "CAMARAS - DETEÇÃO BARCO NA CALDEIRA FORA DOS LIMITES A JUSANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{687, "CAMARAS - DETEÇÃO BARCO NA CALDEIRA DURANTE ECLUSAGEM AUTOMÁTICA DE DESCIDA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{688, "CAMARAS - DETEÇÃO BARCO NA CALDEIRA DURANTE ECLUSAGEM AUTOMÁTICA DE SUBIDA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{689, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{690, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{691, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{692, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{693, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{694, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{695, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{696, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{697, "DETEÇÃO EXCESSO VELOCIDADE ENTRADA MONTANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{698, "DETEÇÃO EXCESSO VELOCIDADE CALDEIRA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{699, "DETEÇÃO EXCESSO VELOCIDADE ENTRADA JUSANTE", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{700, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{701, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{702, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{703, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},
		{704, "RESERVA", "COMANDO_ECLUSA", "EVENTO", "RG_EVENTO_COMANDO_ECLUSA"},

		// ==================== EVENTOS ESGOTO E DRENAGEM (705-736) ====================
		{705, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{706, "REARME AUTOMATICO ARRANCADOR BE1", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{707, "REARME AUTOMATICO ARRANCADOR BE2", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{708, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{709, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{710, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{711, "DISPARO DISJUNTOR QB ALIMENTAÇÃO BOIAS QEBED2", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{712, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{713, "BOMBA ESGOTO 1 LIGADA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{714, "BOMBA ESGOTO 2 LIGADA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{715, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{716, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{717, "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{718, "ORDEM MARCHA BOMBA ESGOTO 1", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{719, "ORDEM MARCHA BOMBA ESGOTO 2", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{720, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{721, "FALTA FORÇA MOTRIZ 3X400VAC BE1", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{722, "FALTA FORÇA MOTRIZ 3X400VAC BE2", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{723, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{724, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{725, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{726, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{727, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{728, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{729, "SISTEMA EM EM MANUAL", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{730, "SISTEMA EM AUTOMATICO", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{731, "SISTEMA DESLIGADO - FORA SERVIÇO", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{732, "BOMBA ESGOTO 1 FORA DE SERVIÇO POR OPERADOR", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{733, "BOMBA ESGOTO 2 FORA DE SERVIÇO POR OPERADOR", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{734, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{735, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
		{736, "RESERVA", "ESGOTO_DRENAGEM", "EVENTO", "RG_EVENTO_ESGOTO_DRENAGEM"},
	}

	// Inserir todos os registros
	fmt.Printf("Inserindo %d registros (496 FALHAS + 240 EVENTOS)...\n", len(registros))
	sucesso := 0
	erros := 0

	for _, registro := range registros {
		var setor_id int
		err := db.QueryRow("SELECT id FROM setores WHERE codigo = $1", registro.Setor).Scan(&setor_id)
		if err != nil {
			log.Printf("⚠️ Setor %s não encontrado para ID %d: %v", registro.Setor, registro.ID, err)
			erros++
			continue
		}

		codigo := fmt.Sprintf("RG_%s_%03d", registro.Setor, registro.ID)

		// Calcular WORD e BIT baseado no ID da falha
		wordIndex := (registro.ID - 1) / 16  // Cada WORD tem 16 bits
		bitIndex := (registro.ID - 1) % 16   // Posição do bit dentro da WORD
		
		_, err = db.Exec(`
			INSERT INTO definicoes_falhas 
			(eclusa_id, setor_id, codigo, tipo, descricao, prioridade, point_index, classe_mensagem, word_index, bit_index)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
			ON CONFLICT (eclusa_id, point_index) DO NOTHING`,
			eclusa_id, setor_id, codigo, registro.Tipo, registro.Descricao, "MEDIA", registro.ID-1, registro.ClasseMensagem, wordIndex, bitIndex)

		if err != nil {
			log.Printf("⚠️ Erro ao inserir ID %d (%s): %v", registro.ID, codigo, err)
			erros++
		} else {
			sucesso++
		}

		// Feedback de progresso a cada 100 registros
		if registro.ID%100 == 0 {
			fmt.Printf("   Progresso: %d/%d registros...\n", registro.ID, len(registros))
		}
	}

	fmt.Printf("\n✅ Inserção concluída: %d sucessos, %d erros\n", sucesso, erros)
	return nil
}

func exibirEstatisticas(db *sql.DB) {
	fmt.Println("📊 ESTATÍSTICAS FINAIS:")
	fmt.Println("========================")

	rows, err := db.Query(`
		SELECT 
			s.nome as setor,
			COUNT(CASE WHEN df.tipo = 'FALHA' THEN 1 END) as falhas,
			COUNT(CASE WHEN df.tipo = 'EVENTO' THEN 1 END) as eventos,
			COUNT(*) as total
		FROM setores s
		LEFT JOIN definicoes_falhas df ON s.id = df.setor_id
		WHERE df.eclusa_id = (SELECT id FROM eclusas WHERE codigo = 'REGUA')
		GROUP BY s.id, s.nome
		ORDER BY s.nome`)

	if err != nil {
		fmt.Printf("❌ Erro ao buscar estatísticas: %v\n", err)
		return
	}
	defer rows.Close()

	total_falhas := 0
	total_eventos := 0
	total_geral := 0

	fmt.Println("\n📍 ECLUSA DA RÉGUA:")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	for rows.Next() {
		var setor string
		var falhas, eventos, total int
		rows.Scan(&setor, &falhas, &eventos, &total)
		fmt.Printf("%-20s: %3d falhas + %3d eventos = %3d\n", setor, falhas, eventos, total)
		total_falhas += falhas
		total_eventos += eventos
		total_geral += total
	}

	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Printf("🎯 TOTAL RÉGUA     : %3d falhas + %3d eventos = %3d\n",
		total_falhas, total_eventos, total_geral)
	fmt.Println("\n🚀 Sistema pronto para integração com PLC!")
}
